### PR TITLE
172 no package for war packaging

### PR DESCRIPTION
**Pull request by scottkurz**

### CODE REVIEW

**Comment by mattbsox** [comment]
Do we want to add this functionality in boost-gradle as well?

**Comment by scottkurz** [comment]
Yeah let's fix Gradle or at least open another issue.

And we should open two issues:

1. package the JAR for JAR packaging type (for EE/MP)
1. provide an optional way to package the JAR for WAR packaging type.

**Comment by scottkurz** [comment]
Thx @mattbsox ..cherry picked that one commit.

**Comment by scottkurz** [comment]
@mattbsox  - Not sure I need to know or should be asking about code that's now removed.. BUT... I'm curious why the JAR was built in the root dir rather than build/libs, since it won't get cleaned..... was that just maybe something done w/o much thought or was there a reason?

**Comment by mattbsox** [comment]
Looks like we're getting the archive name(which gets used as the path later) from the war.archiveName property. Unless we have the packaging properties set in the boost plugin configuration we're packaging the runnable jar in the projectDir rather than build/libs. We can change where we grab the path from war.archiveName to war.archivePath and get the jar to go where ever the war gets put or just set it to go into build/libs everytime.

**Comment by scottkurz** [comment]
>We can change where we grab the path from war.archiveName to war.archivePath and get the jar to go where ever the war gets put or just set it to go into build/libs everytime.

Thanks Matt.. sounds like maybe we hadn't put too much thought into that before... which isn't unjustified as here we are removing this code (for now).. but could do whatever later.  Appreciate your comment.

**Pull request merged**
