### PR TITLE
Handle server package in case server is started by using…

### PR DESCRIPTION
**Pull request by scottkurz**
… alt. output dir

### CODE REVIEW

**Comment by scottkurz** [comment]
On Win10, I still see output like this from the `mvn package` against the started server:
```
[INFO] Building archive for server BoostServer.
[INFO] Unable to archive file C:\boost\boost\boost-maven-plugin\target\it\test-spring-boot-2.0-implicit\target\liberty\wlp\usr\servers\BoostServer\workarea\.sLock due to java.io.IOException: The process cannot access the file because another process has locked a portion of the file.
```

But it completes fine, and the JAR seems good as a runnable Liberty Uber JAR.

**Comment by scottkurz** [comment]
When trying the fix (manually, no automated test), I  get a working runnable JAR, but see:

> 
> [INFO] Building archive for server BoostServer.
> [INFO] CWWKE0070W: The loose file C:\boost\boost\boost-maven\boost-maven-plugin\target\it\test-jaxrs-2.0\target\liberty\wlp\usr\servers\BoostServer\apps\test-jaxrs-2.0-1.0-SNAPSHOT.war.xml is invalid.
> [INFO] Unable to archive file C:\boost\boost\boost-maven\boost-maven-plugin\target\it\test-jaxrs-2.0\target\liberty\wlp\usr\servers\BoostServer\workarea\.sLock due to java.io.IOException: The process cannot access the file because another process has locked a portion of the file.
> [INFO] Server BoostServer package complete in C:\boost\boost\boost-maven\boost-maven-plugin\target\it\test-jaxrs-2.0\target\test-jaxrs-2.0-1.0-SNAPSHOT.jar.
> 

So @ctian,  I see your point...

**Comment by scottkurz** [comment]
Paging @hlhoots  ;)    

I noticed you did some work with the `server package` command recently. 

We noticed using the Maven plugins that, while `server package` complains when you run it against a started server, it seems to work just fine, **as long as** you point it to a different output directory (than the one being used to run the live server).

It could be nice/convenient to have the flexibility to not have to stop the server when packaging.      If that error message is just an overreaction or some code taking an extra-defensive take on things, well, maybe we just ignore it in the short term and who knows, maybe one day fix it.

But I'm not making the case it's _essential_ if there's a good reason we can't stop a started server.

Appreciate if you have any opinion on this issue.. Thanks!

**Comment by hlhoots** [comment]
@scottkurz 

Hey.  I'm not sure on the history/reason of stopping the server before packaging. I will take a look and let you know something early in the New Year!

**Comment by hlhoots** [comment]
Just as an FYI....The CWWKE0070W error shown in Scott's snippet above is a known issue for loose apps.  Issue here for resolution: https://github.com/OpenLiberty/open-liberty/issues/6073

**Comment by scottkurz** [comment]
Thanks @hlhoots !  ...will follow-up in the New Year 👍

**Pull request merged**
